version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_simulador
    restart: always
    environment:
      MYSQL_DATABASE: simulador_credito
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: